# Configurações secretas para o Streamlit Cloud
# Este arquivo é usado para configurações sensíveis

[general]
app_name = "D&D 5e Character Creator"
version = "1.0.0"
description = "Sistema completo para criação de fichas de personagem D&D 5e (2024)"

[theme]
primary_color = "#FF6B6B"
background_color = "#FFFFFF"
secondary_background_color = "#F0F2F6"
text_color = "#262730"