[general]
app_name = "D&D 5e Character Creator"
version = "1.0.0"
description = "Sistema completo para criação de fichas de personagem D&D 5e"

[deployment]
platform = "streamlit_cloud"
auto_deploy = true

[features]
dark_mode = true
multilingual = true
pdf_export = true
character_save = true